services:
  ws-scrcpy:
    image: ws-scrcpy:latest
    container_name: ws-scrcpy
    ports:
      - "8000:8000"
    restart: unless-stopped
    privileged: true
    devices:
      - /dev/bus/usb:/dev/bus/usb
    volumes:
      - ./adbkeys:/root/.android

  ws-scrcpy-dev:
    image: ws-scrcpy-dev:latest
    container_name: ws-scrcpy-dev
    ports:
      - "8000:8000"
    privileged: true
    devices:
      - /dev/bus/usb:/dev/bus/usb
    volumes:
      - ./src:/app/src
      - ./adbkeys:/root/.android
