#!/usr/bin/env node
/* eslint-disable */
// Generates a self-signed certificate for this machine and a run configuration that serves
// ws-scrcpy over HTTPS on 8443 next to the plain HTTP 8000 listener.
//
// Why: Chrome and Edge expose WebCodecs (the only way the browser can decode the iPhone's HEVC
// stream) on secure origins only -- https:// or localhost. Safari does not have that rule, so a
// phone on the LAN works over http:// while a desktop Chrome on the same page reports "no
// WebCodecs video decoder". The certificate carries every IPv4 address and the hostname as SANs
// so the browser warning is a one-time "proceed" per origin.
//
//   npm run setup:https        # writes certs/ws-scrcpy.{key,crt} and config.https.yaml
//   npm run start:https        # dist server with that config
const { execFileSync } = require('node:child_process');
const fs = require('node:fs');
const os = require('node:os');
const path = require('node:path');

const root = path.join(__dirname, '..');
const certDir = path.join(root, 'certs');
const keyPath = path.join(certDir, 'ws-scrcpy.key');
const certPath = path.join(certDir, 'ws-scrcpy.crt');
const configPath = path.join(root, 'config.https.yaml');
const httpPort = Number(process.env.WS_SCRCPY_HTTP_PORT || 8000);
const httpsPort = Number(process.env.WS_SCRCPY_HTTPS_PORT || 8443);

const hostname = os.hostname();
const ipv4 = Object.values(os.networkInterfaces())
    .flat()
    .filter((iface) => iface && iface.family === 'IPv4')
    // LAN addresses first: that is what a desktop browser will type.
    .sort(
        (a, b) =>
            Number(a.internal) - Number(b.internal) ||
            Number(a.address.startsWith('172.')) - Number(b.address.startsWith('172.')),
    )
    .map((iface) => iface.address);
const dnsNames = new Set([hostname, `${hostname}.local`, 'localhost']);
const sans = [...[...dnsNames].map((name) => `DNS:${name}`), ...ipv4.map((ip) => `IP:${ip}`)].join(',');

fs.mkdirSync(certDir, { recursive: true });
if (fs.existsSync(certPath) && !process.argv.includes('--force')) {
    console.log(`Keeping existing ${path.relative(root, certPath)} (pass --force to regenerate).`);
} else {
    execFileSync(
        'openssl',
        [
            'req',
            '-x509',
            '-newkey',
            'rsa:2048',
            '-sha256',
            '-nodes',
            '-days',
            '3650',
            '-keyout',
            keyPath,
            '-out',
            certPath,
            '-subj',
            `/CN=${hostname}`,
            '-addext',
            `subjectAltName=${sans}`,
            '-addext',
            'basicConstraints=CA:FALSE',
            '-addext',
            'keyUsage=digitalSignature,keyEncipherment',
            '-addext',
            'extendedKeyUsage=serverAuth',
        ],
        { stdio: ['ignore', 'ignore', 'inherit'] },
    );
    fs.chmodSync(keyPath, 0o600);
    console.log(`Wrote ${path.relative(root, certPath)} for ${sans}`);
}

// Refuse to write a config the server cannot start with: HttpServer throws on EADDRINUSE.
const net = require('node:net');
const portFree = (port) =>
    new Promise((resolve) => {
        const probe = net.createServer();
        probe.once('error', () => resolve(false));
        probe.listen(port, () => probe.close(() => resolve(true)));
    });
(async () => {
    if (!(await portFree(httpsPort))) {
        console.error(
            `Port ${httpsPort} is already in use on this machine. Pick another: WS_SCRCPY_HTTPS_PORT=8444 npm run setup:https`,
        );
        process.exit(1);
    }
    const config = `# Generated by scripts/setup-https.js -- see README "HTTPS".
# Plain HTTP stays on ${httpPort} (phones, Safari); Chrome/Edge need the HTTPS listener for WebCodecs.
server:
  - secure: false
    port: ${httpPort}
  - secure: true
    port: ${httpsPort}
    options:
      certPath: ${certPath}
      keyPath: ${keyPath}
`;
    fs.writeFileSync(configPath, config);
    console.log(`Wrote ${path.relative(root, configPath)}`);
    console.log(
        `\nStart with:  npm run start:https\nThen open:   https://${ipv4[0] || hostname}:${httpsPort}/  (accept the self-signed certificate once)`,
    );
})();
